# Generated by Django 4.2.10 on 2024-03-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
